### ISSUE TITLE
Syntax error export serverMiddleware from './Router.js';

### ISSUE THREAD

**Issue by mayyyc** [maximenajim/Universal-JavaScript-with-React-Node-and-Redux#1]
Hi I ran 'npm install' and 'npm start' but got an syntax error for exporting functions.

I didn't modify any code, anyone knows what's going on???
It seems like propblem with babel? But the import in the first line is fine, it's weird.

## Here is the errer message:

192-168-1-4:05_react_redux_server junwenchen$ npm start

> universal-react@1.0.0 start /Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server
> node server/index.js

/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/client/index.js: Unexpected token, expected { (2:7)
  1 | import 'isomorphic-fetch';
> 2 | export serverMiddleware from './Router.js';
    |        ^
  3 | 
  4 | if (module.hot) {
  5 | 	module.hot.accept();
    at Parser.pp$5.raise (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expect (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:1749:33)
    at Parser.pp$1.parseExportSpecifiers (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:2830:8)
    at Parser.pp$1.parseExport (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:2658:28)
    at Parser.pp$1.parseStatement (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:1884:74)
    at Parser.pp$1.parseBlockBody (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:1673:17)
    at parse (/Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/node_modules/babylon/lib/index.js:7305:37)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! universal-react@1.0.0 start: `node server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the universal-react@1.0.0 start script 'node server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the universal-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs universal-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls universal-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/junwenchen/Downloads/Universal-JavaScript-with-React-Node-and-Redux-master/05_react_redux_server/npm-debug.log

![image](https://user-images.githubusercontent.com/16255652/30190755-b10eb65a-947f-11e7-82c9-6770c1d8f448.png)

**Comment by mayyyc** [comment]
I solved the problem but modify "export serverMiddleware from './Router.js';" to "import './Router.js'". 

I don't know if it's a right way to do that but it works... 

## Then I got another syntax error: 
![image](https://user-images.githubusercontent.com/16255652/30191430-0d887c46-9484-11e7-9e0c-1b2473da21c8.png)

I have no idea what is wrong. I thought it was the problem compiling jsx element but I checked the webpack.config, there is a module handling .jsx/.js, it should be alright, right?

  module: {
    loaders: [{
      test: /\.js?$/,
      loader: 'babel-loader',
      include: path.join(__dirname, 'client'),
      query: {
        plugins: [
          ['react-transform', {
            transforms: [{
              transform: 'react-transform-hmr',
              // If you use React Native, pass 'react-native' instead:
              imports: ['react'],
              // This is important for Webpack HMR:
              locals: ['module'],
            }],
          }],
        ],
      },
    }],
  },
![image](https://user-images.githubusercontent.com/16255652/30191575-ff9ff11c-9484-11e7-8e0b-2fa8d21d3306.png)

**Comment by maximenajim** [comment]
@MMMayC thank you for providing this feedback.  There was a `.babelrc` file missing from the github repo.  I've added the file now, which should resolve the issue you are seeing.  Thanks again.

**Comment by ava-sig** [comment]
please update the packt codefiles as well because this was a real hassle.
I know 2 years have passed but people doing your tutorial right now are stuck without your babelrc
